romium.launch(headless=False)
            page = browser.new_page()
            page.goto("https://www.indianrail.gov.in/enquiry/PNR/PnrEnquiry.html?locale=en")
            page.fill("#inputPnrNo",str(pnr))
            page.locator("#modal1").click()
            page.locator("#CaptchaImgID").screenshot(path="captcha.png")
            ans = captcha_solver()
            page.wait_for_timeout(3000)
            page.fill("#inputCaptcha", str(ans))
            page.locator("#submitPnrNo").click()
            passenger_titles = page.locator("#psgnDetailsTable>>tbody")
            message = (passenger_titles.inner_text())
            page.wait_for_timeout(6000)
            status_list.ap